name: "Тест-кейс"
description: "Шаблон для оформления тест-кейсов"
title: "[TC] "
labels: ["test", "priority:medium"]

body:
  - type: textarea
    id: preconditions
    attributes:
      label: "Предусловия"
      placeholder: "Например: пользователь с ролью Customer; товар в корзине…"

  - type: textarea
    id: steps
    attributes:
      label: "Шаги выполнения"
      placeholder: |
        1) Перейти на страницу …
        2) Нажать …
        3) Проверить …
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Ожидаемый результат"
      placeholder: "Что должно произойти?"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Приоритет"
      options: ["High", "Medium", "Low"]
      default: 1
